applications: map(include('application'))
---
application:
  description: str()
  version: str(required=False)
  endpoints: map(include('endpoint'), required=False)

endpoint:
  protocol: str()
  port: int()
