deployments: map(include('deployment'))
---
deployment:
  product: include('product')
  applications: list(include('deployment_application'))
  description: str(required=False)
---
product:
  vendor: str()
  family: str()
  edition: str()
  version: str()
---
deployment_application:
  application: str()
  version: str(required=False)
  configuration: include('application_configuration', required=False)

---
application_configuration:
  contextPath: regex('^/.*$') 
