applications:

  Authentication:
    description: Authentication and identity service.

    endpoints:
      https:
        protocol: HTTPS
        port: 8444

      metrics:
        protocol: HTTP
        port: 9090

  Portal:
    description: User-facing REST API for campaign management.

    endpoints:
      https:
        protocol: HTTPS
        port: 8443

      metrics:
        protocol: HTTP
        port: 9090
  
  CampaignManager:
    description: Business logic and campaign lifecycle management.

    endpoints:
      rest:
        protocol: HTTP
        port: 8080

      metrics:
        protocol: HTTP
        port: 9090
  
  CallSimulation:
    description: Simulates outbound voice campaign execution.

    endpoints:
      rest:
        protocol: HTTP
        port: 8081

      metrics:
        protocol: HTTP
        port: 9090

  PostgreSQL:
    description: Persistent campaign database.

    endpoints:
      sql:
        protocol: TCP
        port: 5432