services:
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    volumes:
    # Provisioning
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      
    # Dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  loki:
    image: grafana/loki:3.5.0
    command:
      - -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro

  promtail:
    image: grafana/promtail:3.5.0
    command:
      - -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log/infra:ro
