services:
  portal:
    image: out-dialer/portal:0.1
    hostname: portal
    networks:
      dmz: {}
      internal: {}
    ports:
    - 8443:8443
    - 8444:8444
    - 9090:9090
  campaign:
    image: out-dialer/campaign-manager:0.1
    hostname: campaign
    networks:
      internal: {}
      database: {}
    ports:
    - 8080:8080
    - 19090:9090
  call_simulator:
    image: out-dialer/call-simulator:0.1
    hostname: call_simulator
    networks:
      internal: {}
    ports:
    - 8081:8081
    - 29090:9090
  database:
    image: postgres:17
    hostname: database
    networks:
      database: {}
    ports:
    - 5432:5432
networks:
  dmz: {}
  internal: {}
  database: {}
